# Git branch - ブランチ名を表示
[git_branch]
format = "on [$branch]($style)"
style = "bold purple"

# Git commit - 短縮ハッシュを表示
[git_commit]
commit_hash_length = 7
format = " [\\[$hash\\]]($style)"
style = "green"

only_detached = false  # detached HEADでなくても常に表示


# Git status - インジケータを表示

[git_status]

format = "[\\[$all_status$ahead_behind\\]]($style) "

style = "red"
conflicted = "="
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"

untracked = "?"
stashed = "\\$"

modified = "!"
staged = "+"
renamed = "»"

deleted = "✘"
